# Generated by Django 3.2.9 on 2021-11-01 20:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0003_rename_attendancegrabberconfig_attendancegrabberdata'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AttendanceGrabberData',
            new_name='Courses',
        ),
    ]
