# Generated by Django 3.2.9 on 2021-11-01 21:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0005_rename_courses_course'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Course',
            new_name='UserData',
        ),
        migrations.AlterModelOptions(
            name='userdata',
            options={'permissions': [('can_view_all_attendance', 'Can view all attendance')], 'verbose_name': 'user data', 'verbose_name_plural': 'user data'},
        ),
    ]
