# Generated by Django 3.2.9 on 2021-11-05 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20211102_0503'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='timetable',
            field=models.JSONField(default=list),
        ),
    ]
